// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/antonmisa/cliurlfetcher/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// QueueReader is an autogenerated mock type for the QueueReader type
type QueueReader struct {
	mock.Mock
}

// Pop provides a mock function with given fields:
func (_m *QueueReader) Pop() (entity.Task, bool) {
	ret := _m.Called()

	var r0 entity.Task
	var r1 bool
	if rf, ok := ret.Get(0).(func() (entity.Task, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() entity.Task); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.Task)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewQueueReader creates a new instance of QueueReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueReader {
	mock := &QueueReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
