// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/antonmisa/cliurlfetcher/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// QueueWriter is an autogenerated mock type for the QueueWriter type
type QueueWriter struct {
	mock.Mock
}

// Push provides a mock function with given fields: _a0
func (_m *QueueWriter) Push(_a0 entity.Task) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Task) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQueueWriter creates a new instance of QueueWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueWriter {
	mock := &QueueWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
